config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  get    'admin_home' => 'students#admin_home'
  get    'student_home'  => 'students#student_home'
  get    'admin_index' => 'students#admin_index'
  get    'book_filters' => 'books#filters'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'

  get 'books/history/:id' => 'books#history'
  get '/books/:isbn', to: "books#show"

  get 'students/history/:id' => 'students#history'
  get 'students/delete_admin/:id' => 'students#delete_admin'

  resources :checkout_histories
  resources :students
  get 'students/delete_admin/:id' => 'students#delete_admin'

  resources :books
  get 'books/history/:id' => 'books#history'
  get 'students/history/:id' => 'students#history'

  post '/books/:id' => 'books#checkout'
  resources :shelves

end

app/models/student.rb
class Student < ActiveRecord::Base

  has_secure_password
  EMAIL_FORMAT = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i
  validates :name, :presence => true, :uniqueness => true, :length => { :in => 2..50 }
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_FORMAT
  validates :student_type, :inclusion  => { :in => [ 'U','A','P' ] }

  has_many :checkout_histories
  has_many :books, through: :checkout_histories

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  wrap_parameters :student, include: [:name, :email, :password, :password_confirmation, :student_type]

  # GET /students
  # GET /students.json
  def index
    if check_if_admin
      @students = Student.all
    else
      respond_to do |format|
        format.html{redirect_to student_home_path, notice: "Access to requested link is denied" }
      end
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    if check_if_student || check_if_admin
      @students = Student.where(id: params[:id])
    else
      respond_to do |format|
        format.html{redirect_to student_home_path, notice: "Access to requested link is denied" }
      end
    end
  end

  # GET /students/new
  def new
    @student = Student.new
    # Even students who are not logged in can access the form and hence no authorization
  end

  # GET /students/1/edit
  def edit
    if check_if_student
      if params[:id].to_s != Student.find_by_id(session[:current_student_id]).id.to_s
        respond_to do |format|
          format.html{redirect_to student_home_path, notice: "No sufficient permissions to edit other students"}
        end
      end
    end
  end

  # POST /students
  # POST /students.json
  def create
    if ['A'].include?(student_params[:student_type])
      if session[:current_student_id].nil?
        redirect_to login_path, notice: "Only logged in admins can add new admins"
      elsif check_if_student
        redirect_to student_home_path, notice: "No sufficient permissions to add admin"
      elsif check_if_admin
        @student = Student.new(student_params)
        if @student.save
          #Tell the studentMailer to send a welcome email after save
          StudentMailer.welcome_email(@student).deliver_later
          redirect_to admin_home_path, notice: 'Admin was successfully created'
        else
          render :new
        end
      end
    elsif ['P'].include?(student_params[:student_type])
      if session[:current_student_id].nil?
        redirect_to login_path, notice: "Preconfigured admin cannot be created"
      elsif check_if_student
        redirect_to student_home_path, notice: "Preconfigured admin cannot be created"
      elsif check_if_admin
        redirect_to admin_home_path, notice: "Preconfigured admin cannot be created"
      end
    elsif ['U'].include?(student_params[:student_type])
      @student = Student.new(student_params)
      respond_to do |format|
        if @student.save
          #Tell the studentMailer to send a welcome email after save
          StudentMailer.welcome_email(@student).deliver_later
          if session[:current_student_id].nil?
            format.html { redirect_to login_path, notice: 'Student was successfully created. Login to access the system.' }
          else
            format.html {redirect_to :back, notice: 'Student was successfully created. Login to access the system.' }
          end
        else
          format.html { render :new }
        end
    end
    end
    end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    if session[:current_student_id].nil?
      if check_if_admin
      redirect_to login_path, notice: "Only logged in admins can edit admins"
      else
        redirect_to login_path, notice: "Only logged in students can edit students"
      end
    end

    if params[:id].to_s != Student.find_by_id(session[:current_student_id]).id.to_s
       if check_if_student
        redirect_to student_home_path,notice: "students do not have permissions to update other students"
      elsif check_if_admin
        redirect_to admin_home_path,notice: "Admins do not have permissions to update other students"
      end
    end

    if ['A','P'].include?(student_params[:student_type]) && check_if_student
        redirect_to student_home_path, notice: "You do not have sufficient permission to edit admins"
    elsif  student_params[:student_type] == 'U' && check_if_admin
        redirect_to admin_home_path, notice: "You do not have sufficient permission to edit students"
    elsif student_params[:student_type] == 'P'
      redirect_to admin_home_path, notice: "Preconfigured admin details cannot be updated"
    else
      respond_to do |format|
        if @student.update(student_params)
          format.html { redirect_to student_home_path, notice: 'Student was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end
  end

  def admin_index
    if check_if_admin
      @students = Student.where(student_type: ['A','P'])
    else
      respond_to do |format|
        format.html{redirect_to student_home_path, notice: "Access to requested link is denied" }
      end
    end
  end
  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    if check_if_admin
      @checkout_histories=CheckoutHistory.find_by_email(@student.email);
      if @checkout_histories.nil?
      @student.destroy
    respond_to do |format|
      format.html { redirect_to students_path, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end

      else
      @checkout_histories=CheckoutHistory.all
      @checkout_histories.each do |checkout_history|
          if @checkout_histories.last == checkout_history

          puts checkout_history.return_timestamp
          puts DateTime.new(9999,12,31).utc
          puts checkout_history.return_timestamp=='9999-12-31T00:00:00+00:00'


          if !(checkout_history.return_timestamp=='9999-12-31T00:00:00+00:00')
          @student.destroy
          respond_to do |format|
            format.html { redirect_to students_path, notice: 'Student was successfully destroyed.' }
            format.json { head :no_content }
          end
          else
            respond_to do |format|
              format.html { redirect_to students_path, notice: 'Student cannot be destroyed as he has a checked out book.' }
              format.json { head :no_content }
            end
          end
      end
      end
    end
    end
    end

  def delete_admin
if check_if_admin
      @student=Student.find_by_id(params[:id])
      @checkout_histories=CheckoutHistory.find_by_email(@student.email);
      if @checkout_histories.nil?
      @student.destroy
    respond_to do |format|
      format.html { redirect_to admin_index_path, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end

      else
      @checkout_histories=CheckoutHistory.all
      @checkout_histories.each do |checkout_history|
          if @checkout_histories.last == checkout_history

          puts checkout_history.return_timestamp
          puts DateTime.new(9999,12,31).utc
          puts checkout_history.return_timestamp=='9999-12-31T00:00:00+00:00'


          if !(checkout_history.return_timestamp=='9999-12-31T00:00:00+00:00')
          @student.destroy
          respond_to do |format|
            format.html { redirect_to admin_index_path, notice: 'Student was successfully destroyed.' }
            format.json { head :no_content }
          end
          else
            respond_to do |format|
              format.html { redirect_to admin_index_path, notice: 'Student cannot be destroyed as he has a checked out book.' }
              format.json { head :no_content }
            end
          end
      end
      end
    end
    end

end

  def history
    @student = Student.find(params[:id])
  end

  def admin_home
    if !check_if_student
      @students = Student.where(student_type: ['A','P'])
    else
      respond_to do |format|
        format.html{redirect_to student_home_path, notice: "Access to requested link is denied" }
      end
    end
  end

  def student_home
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:email, :name, :password, :password_confirmation, :student_type)
    end

    def check_if_student
      return true if ['U'].include? Student.find_by_id(session[:current_student_id]).student_type
    end

    def check_if_admin
      return true if ['A','P'].include? Student.find_by_id(session[:current_student_id]).student_type
    end
    def check_if_pre_configured_admin
      return true if Student.find_by_id(session[:current_student_id]).student_type == 'P'
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<div class="col">

  <%= form_for(@student) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    <hr />

    <div class='text-right'>
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%if @student.student_type=='P' || @student.student_type=='A' %>
      <%= link_to 'Back', admin_home_path, class: 'btn btn-default'%>
    <% end %>
    <%if @student.student_type=='U' %>
      <%= link_to 'Back', student_home_path, class: 'btn btn-default'%>
    <% end %>
    </div>
  <% end %>

app/views/students/admin_home.html.erb
<%= provide(:title, "Welcome") %>
<ul class="list-group">
<h2>My profile</h2>
<li class="list-group-item"><%= link_to 'View/Edit my profile', edit_student_path(session[:current_student_id]) %><br/></li>
<br/>
<h2>Manage Admins</h2>
<li class="list-group-item"><%= link_to 'Add new Admin',   new_student_path %><br/></li>
<li class="list-group-item"><%= link_to 'View list/See details/Delete admins', admin_index_path%><br/></li>
<br/>
<h2>Manage Library Books</h2>
<li class="list-group-item"><%= link_to 'Add new book', new_book_path %><br/></li>
<li class="list-group-item"><%= link_to 'View list of books', books_path %><br/></li>
<li class="list-group-item"><%= link_to 'View book details', books_path %><br/></li>
<li class="list-group-item"><%= link_to 'View Checkout History for Books', checkout_histories_path %><br/></li>
<li class="list-group-item"><%= link_to 'Checkout/Return Books', books_path %></li>
<br/>
<h2>Library Members</h2>
<li class="list-group-item"><%= link_to 'View Checkout history for a student', students_path %><br/></li>
<li class="list-group-item"><%= link_to 'Delete a book', books_path %><br/></li>
<li class="list-group-item"><%= link_to 'List all library members', students_path %><br/></li>
<li class="list-group-item"><%= link_to 'Delete a member', students_path %><br/></li>
<br/>
<h2>Shelves</h2>
<li class="list-group-item"><%= link_to 'View Shelves', shelves_path %><br/></li>
</ul>

app/views/students/admin_index.html.erb
<h1>Listing Students</h1>

<table>
  <thead>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th>student type</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @students.each do |student| %>

      <tr>
        <td><%= student.email %></td>
        <td><%= student.name %></td>
        <td><%= student.student_type %></td>
        <td><%= link_to 'Show', student %></td>
        <% if student.student_type == "A"%>
          <% if session[:current_student_id]!=student.id %>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy',controller: "students", action: "delete_admin",id: student.id, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
            <%end%>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', admin_home_path %>

app/views/students/edit.html.erb
<div class="contain clearfix pad4y col-sm-8 col-sm-offset-2">

<h1>Editing Student</h1>

<%= render 'form' %>

</div>

app/views/students/history.html.erb
<h1>Listing Checkout Histories</h1>

<table>
  <thead>
  <tr>
    <th>Email</th>
    <th>Isbn</th>
    <th>Checkout timestamp</th>
    <th>Return timestamp</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%if @checkout_histories = CheckoutHistory.all%>
    <% @checkout_histories.each do |checkout_history| %>
      <%if checkout_history.email == @user.email%>
          <tr>
            <td><%= checkout_history.email %></td>
            <td><%= checkout_history.isbn %></td>
            <td><%= checkout_history.checkout_timestamp %></td>
            <td><%= checkout_history.return_timestamp %></td>
            </tr>
          <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/students/index.html.erb
<h1>Listing Students</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.email %></td>
        <td><%= student.name %></td>
        <td><%= student.student_type %></td>
        <td><%= link_to 'Show', student %></td>
        <% if student.student_type == "U"%>
            <%if session[:current_student_id]!=student.id%>
              <td><%= link_to 'Edit', edit_student_path(student) %></td>
              <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/students/show.html.erb
<%= render 'form' %>

<%if @student.student_type=='P' || @student.student_type=='A' %>
<%= link_to 'Back', admin_home_path%>
<% end %>
<%if @student.student_type=='U' %>
<%= link_to 'Back', student_home_path%>
<% end %>

app/views/students/student_home.html.erb
<%= provide(:title, "Welcome") %>

<ul class="list-group">
<h2>My Profile</h2>
<li class="list-group-item"><%= link_to 'View/Edit My Profile', edit_student_path(session[:current_student_id]) %><br/></li>
<h2>Explore Library</h2>
<li class="list-group-item"><%= link_to 'Checkout a book', books_path %><br/></li>
<li class="list-group-item"><%= link_to 'Return a book', checkout_histories_path %><br/></li>
<li class="list-group-item"><%= link_to 'Explore Books', books_path %><br/></li>
<% @student = Student.find_by_id(session[:current_student_id]) %>
<% @checkout_history = CheckoutHistory.where(@student.email) %>
<li class="list-group-item"><%= link_to 'View my checkout history', checkout_histories_path %></li>
<li class="list-group-item"><%= link_to 'Find Shelf', shelves_path %><br/></li>
</ul>

app/views/students/user_home.html.erb
<%= provide(:title, "Welcome") %>

<h4>My Profile</h4>
<%= link_to 'View my profile', student_path(session[:current_student_id]) %><br/>
<%= link_to 'Edit my profile', edit_student_path(session[:current_student_id]) %><br/>
<h4>Enlighten me</h4>
<%= link_to 'Checkout a book', books_path %><br/>
<%= link_to 'Check-in a book', books_path %><br/>
<%= link_to 'Explore Books', books_path %><br/>
<% @student=Student.find_by_id(session[:current_student_id])%>
<% @checkout_history=CheckoutHistory.where(@student.email)%>
<%= link_to 'View my checkout history', checkout_histories_path %>