config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  get    'admin_home' => 'students#admin_home'
  get    'student_home'  => 'students#student_home'
  get    'admin_index' => 'students#admin_index'
  get    'book_filters' => 'books#filters'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'

  get 'books/history/:id' => 'books#history'
  get '/books/:isbn', to: "books#show"

  get 'students/history/:id' => 'students#history'
  get 'students/delete_admin/:id' => 'students#delete_admin'

  resources :checkout_histories
  resources :students
  get 'students/delete_admin/:id' => 'students#delete_admin'

  resources :books
  get 'books/history/:id' => 'books#history'
  get 'students/history/:id' => 'students#history'

  post '/books/:id' => 'books#checkout'
  resources :shelves

end

app/models/checkout_history.rb
class CheckoutHistory < ActiveRecord::Base

  belongs_to :student
  belongs_to :book

end

app/controllers/checkout_histories_controller.rb
class CheckoutHistoriesController < ApplicationController
  before_action :set_checkout_history, only: [:show, :edit, :update, :destroy]

  # GET /checkout_histories
  # GET /checkout_histories.json
  def index
    @checkout_histories = CheckoutHistory.all
  end

  # GET /checkout_histories/1
  # GET /checkout_histories/1.json
  def show


  end

  # GET /checkout_histories/new
  def new
    @checkout_history = CheckoutHistory.new
  end

  # GET /checkout_histories/1/edit
  def edit
  end

  # POST /checkout_histories
  # POST /checkout_histories.json
  def create
    @checkout_history = CheckoutHistory.new(checkout_history_params)

    respond_to do |format|
      if @checkout_history.save
        format.html { redirect_to @checkout_history, notice: 'Checkout history was successfully created.' }
        format.json { render :show, status: :created, location: @checkout_history }
      else
        format.html { render :new }
        format.json { render json: @checkout_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checkout_histories/1
  # PATCH/PUT /checkout_histories/1.json
  def update
    respond_to do |format|
      if @checkout_history.update(checkout_history_params)
        format.html { redirect_to @checkout_history, notice: 'Checkout history was successfully updated.' }
        format.json { render :show, status: :ok, location: @checkout_history }
      else
        format.html { render :edit }
        format.json { render json: @checkout_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkout_histories/1
  # DELETE /checkout_histories/1.json
  def destroy
    @checkout_history.destroy
    respond_to do |format|
      format.html { redirect_to checkout_histories_url, notice: 'Checkout history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def book_history

    @checkout_histories = CheckoutHistory.find_by_id(params[:id])
  end
  helper_method :book_history

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkout_history
      @checkout_history = CheckoutHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def checkout_history_params
      params.permit(:email, :isbn, :checkout_timestamp, :due_date)
    end
end

app/helpers/checkout_histories_helper.rb
module CheckoutHistoriesHelper
end

app/views/checkout_histories/_form.html.erb
<%= form_for(@checkout_history) do |f| %>
  <% if @checkout_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checkout_history.errors.count, "error") %> prohibited this checkout_history from being saved:</h2>

      <ul>
      <% @checkout_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :checkout_timestamp %><br>
    <%= f.text_field :checkout_timestamp %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.text_field :due_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checkout_histories/edit.html.erb
<h1>Editing Checkout History</h1>

<%= render 'form' %>

<%= link_to 'Show', @checkout_history %> |
<%= link_to 'Back', checkout_histories_path %>

app/views/checkout_histories/index.html.erb
<h1>My Checkout Histories</h1>
<div class="row">

<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Isbn</th>
      <th>Title</th>
      <th>Checkout Date</th>
      <th>Due Date</th>
      <th>Returned Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% @student = Student.find_by_id(session[:current_student_id]) %>
  <tbody>
    <% @checkout_histories.each do |checkout_history| %>
      <tr>

        <% if(checkout_history.email == @student.email || @student.student_type=='A' || @student.student_type=='P') %>
        <td><%= checkout_history.email %></td>
        <td><%= checkout_history.isbn %></td>
            <%@book=Book.find_by_isbn(checkout_history.isbn)%>
            <td><%= @book.title %></td>
        <td><%= checkout_history.checkout_timestamp %></td>
        <td><%= checkout_history.due_date %></td>
        <td><%= checkout_history.returned_date %><td>
        <% @book = Book.find_by(isbn: checkout_history.isbn) %>
        <% if @book.available == false %>
        <td>  <%= link_to 'Return', book_path(@book), method: :post, data: { confirm: 'Are you sure you would like to return this book?'}, :class => 'btn btn-primary' %></td>
        <% else %>
        <td> Returned </td>
        <% end %>
        <% end %>

        <% if(@student.student_type=='A' || @student.student_type=='P') %>
            <td><%= link_to 'Edit', edit_checkout_history_path(checkout_history) %></td>
            <td><%= link_to 'Destroy', checkout_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/checkout_histories/new.html.erb
<h1>New Checkout History</h1>

<%= render 'form' %>

<%= link_to 'Back', checkout_histories_path %>

app/views/checkout_histories/show.html.erb
<p>
  <strong>Email:</strong>
  <%= @checkout_history.email %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @checkout_history.isbn %>
</p>

<p>
  <strong>Checkout date:</strong>
  <%= @checkout_history.checkout_timestamp %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @checkout_history.due_date %>
</p>

<p>
  <strong>Returned date:</strong>
  <% @checkout_history.returned_date %>
<p>


<%= link_to 'Back', admin_home_path %>