config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  get    'admin_home' => 'students#admin_home'
  get    'student_home'  => 'students#student_home'
  get    'admin_index' => 'students#admin_index'
  get    'book_filters' => 'books#filters'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'

  get 'books/history/:id' => 'books#history'
  get '/books/:isbn', to: "books#show"

  get 'students/history/:id' => 'students#history'
  get 'students/delete_admin/:id' => 'students#delete_admin'

  resources :checkout_histories
  resources :students
  get 'students/delete_admin/:id' => 'students#delete_admin'

  resources :books
  get 'books/history/:id' => 'books#history'
  get 'students/history/:id' => 'students#history'

  post '/books/:id' => 'books#checkout'
  resources :shelves

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The SWE Library System by Group 9 (Spring 2016)
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "SWE Library System", root_url, id: "logo" %>
      <nav>
       <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_url %></li>
          <li><%= link_to "Categories & Languages", book_filters_path %></li>
            <% if !current_page?(login_path) && !session[:current_student_id].nil? %>
              <% if ['A','P'].include?(Student.find_by_id(session[:current_student_id]).student_type) %>
                <li><%= link_to 'View Account', admin_home_path %></li>
                  <% else %>
                    <li><%= link_to 'My Account', student_home_path %></li>
                    <%end%>
                <li><%= link_to 'Signout', logout_path %></li>
                <% else %>
              <li><%= link_to "Login", login_path %></li>
          <%end%>
        </ul>
      </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Swe Library System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
    
<%= render 'layouts/header' %>

<div class="container">

  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
  <%= yield %>

  <%= render 'layouts/footer' %>

</div>

</body>

</html>